paperposts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('papers.urls')),
    path('admin/', admin.site.urls),
    
]

papers/urls.py
from django.urls import path
from .  import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>/", views.post_details, name='post_details'),
    path('create_post', views.create_post, name='create_post'),
]

papers/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    post_title = models.CharField(max_length = 50)
    color = models.CharField(max_length=7, default='#FFD700')
    def __str__(self):
        return self.post_title

class Task(models.Model):
    STATUS_CHOICES = {
        'NS': 'Not Started',
        'DO': 'Doing',
        'DN': 'Done',
        'CA': 'Canceled'
    }
    
    DIFF_LEVEL_CHOICES = {
        'VE': 'Very Easy',
        'E' : 'Easy',
        'M' : 'Medium',
        'H' : 'Hard',
        'VH' : 'Very Hard'
    }
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(max_length = 150)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=STATUS_CHOICES['NS'])
    difficult_level = models.CharField(max_length = 2, choices=DIFF_LEVEL_CHOICES)
    deadline = models.DateTimeField("deadline")
    
    def __str__(self):
        return self.text
    

papers/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post, Task

# Create your views here.
def index(request):

    posts = Post.objects.all()
    return render(request, 'papers/index.html', {'posts': posts})

def post_details(request, post_id):
    post = Post.objects.get(pk=post_id)

    return render(request, 'papers/post_details.html', {'post':post})

def create_post(request):
    if request.method == 'POST':
        title = request.POST['post_name']
        color = request.POST['color_input']
        Post.objects.create(post_title=title, color=color).save()
        return redirect('/')
    else:
        return render(request, 'papers/create_post.html')

templates/papers/create_post.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
    <link rel = "stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>
        <a class='first_title' href="{% url 'index' %}">Paper Notes</a>
    </h1>
    <h2> Create new post </h2>
    <div>
        <form method='POST' action='create_post'>
            {% csrf_token %}
            <p>Post Name:</p>
            <input type='text' name='post_name'/>
            <p>Choose color:</p>
            <input type="color" id="color_input" name="color_input" value="#ff0000"/><br><br>
            <input type='submit' value='Create'/>
        </form>
    </div>
</body>
</html>

templates/papers/index.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link rel = "stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>
        <a class='first_title' href="{% url 'index' %}">Paper Notes</a>
    </h1>
    <div class="post-its-container">
        {% for post in posts %}
            <a class="post-it" href = "{% url 'post_details' post.id %}" style="background-color:{{post.color}}">
                <p class='post-title'>{{post.post_title}}</p>
                <div class="post-it-content">
                    <ul>
                        {% for task in post.task_set.all %}
                            <li>{{task.text}} - deadline: {{task.deadline}} | level: {{task.get_difficult_level_display}} | status: {{task.get_status_display}}</li>
                        {%endfor%}  
                    </ul>
                </div>
            </a>
        {% endfor %}
        <a href="{% url 'create_post' %}" class="add-button">   
            <div >
                <spam class="plus-symbol">+</spam>
            </div>
        </a>
    </div>
</body>
</html>

templates/papers/post_details.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    <link rel = "stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <h1>
        <a class='first_title' href="{% url 'index' %}">Paper Notes</a>
    </h1>
    <div>
        <p class = 'details'>{{post.post_title}}</p>
        <div class="post-it-content">
            <ul>
                {% for task in post.task_set.all %}
                    <li>{{task.text}} - deadline: {{task.deadline}} | level: {{task.get_difficult_level_display}} | status: {{task.get_status_display}}</li>
                {%endfor%}  
            </ul>
        </div>
    </div>
</body>
</html>